# This is a basic workflow to help you get started with Actions

name: Build & Release

permissions:
  contents: write # need for create release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "release" branch
  push:
    tags:
      - 'release-*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-release:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup PowerShell module cache
        id: cacher
        uses: actions/cache@v3
        with:
          path: "C:/Users/runneradmin/Documents/WindowsPowerShell/Modules"
          key: ${{ runner.os }}-Powershell-Module-PS2EXE
      - name: Install  ps2exe
        if: steps.cacher.outputs.cache-hit != 'true'
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module ps2exe -Scope CurrentUser
        shell: powershell
        
      - name: Build
        run: ./build.ps1
        shell: powershell
        
      - name: Test
        run: |
          ls build/ectray
          ls release
        
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "release/ectray*.zip"
